


countries = Country.create([
  {name: "Andorra", flag: "ad"},
  {name: "Arab Emirates", flag: "ae"},
  {name: "Afghanistan", flag: "af"},
  {name: "Antigua and Barbuda", flag: "ag"},
  {name: "Anguilla", flag: "ai"},
  {name: "Albania", flag: "al"},
  {name: "Armenia", flag: "am"},
  {name: "Angola", flag: "ao"},
  {name: "Antarctica", flag: "aq"},
  {name: "Argentina", flag: "ar"},
  {name: "American Samoa", flag: "as"},
  {name: "Austria", flag: "at"},
  {name: "Australia", flag: "au"},
  {name: "Aruba", flag: "aw"},
  {name: "Aland Islands", flag: "ax"},
  {name: "Azerbaijan", flag: "az"},
  {name: "Bosnia and Herzegovina", flag: "ba"},
  {name: "Barbados", flag: "bb"},
  {name: "Bangladesh", flag: "bd"},
  {name: "Belgium", flag: "be"},
  {name: "Bulgaria", flag: "bg"},
  {name: "Burkina Faso", flag: "bf"},
  {name: "Bahrain", flag: "bh"},
  {name: "Burundi", flag: "bi"},
  {name: "Benin", flag: "bj"},
  {name: "Bermuda", flag: "bm"},
  {name: "Brunei", flag: "bn"},
  {name: "Bolivia", flag: "bo"},
  {name: "Brazil", flag: "br"},
  {name: "Bahamas", flag: "bs"},
  {name: "Bhutan", flag: "bt"},
  {name: "Botswana", flag: "bw"},
  {name: "Belarus", flag: "by"},
  {name: "Belize", flag: "bz"},
  {name: "Canada", flag: "ca"},
  {name: "Switzerland", flag: "ch"},
  {name: "Cote d'Ivoire", flag: "ci"},
  {name: "Cook Islands", flag: "ck"},
  {name: "Chile", flag: "cl"},
  {name: "Cameroon", flag: "cm"},
  {name: "China", flag: "cn"},
  {name: "Colombia", flag: "co"},
  {name: "Costa Rica", flag: "cr"},
  {name: "Cuba", flag: "cu"},
  {name: "Cape Verde", flag: "cv"},
  {name: "Czech Republic", flag: "cz"},
  {name: "Germany", flag: "de"},
  {name: "Djibouti", flag: "dj"},
  {name: "Denmark", flag: "dk"},
  {name: "Dominica", flag: "dm"},
  {name: "Dominican Republic", flag: "do"},
  {name: "Algeria", flag: "dz"},
  {name: "Ecuador", flag: "ec"},
  {name: "Estonia", flag: "ee"},
  {name: "Egypt", flag: "eg"},
  {name: "Western Sahara", flag: "eh"},
  {name: "Eritrea", flag: "er"},
  {name: "Spain", flag: "es"},
  {name: "Ethiopia", flag: "et"},
  {name: "Finland", flag: "fi"},
  {name: "Fiji", flag: "fj"},
  {name: "Falkland Islands", flag: "fk"},
  {name: "Micronesia", flag: "fm"},
  {name: "Faroe", flag: "fo"},
  {name: "France", flag: "fr"},
  {name: "Gabon", flag: "ga"},
  {name: "Great Britain", flag: "gb"},
  {name: "Grenada", flag: "gd"},
  {name: "Georgia", flag: "ge"},
  {name: "French Guiana", flag: "gf"},
  {name: "Guernsey", flag: "gg"},
  {name: "Ghana", flag: "gh"},
  {name: "Gibraltar", flag: "gi"},
  {name: "Greenland", flag: "gl"},
  {name: "Gambia", flag: "gm"},
  {name: "Guinea", flag: "gn"},
  {name: "Equatorial Guinea", flag: "gq"},
  {name: "Greece", flag: "gr"},
  {name: "South Georgia", flag: "gs"},
  {name: "Guatemala", flag: "gt"},
  {name: "Guam", flag: "gu"},
  {name: "Guinea-Bissau", flag: "gw"},
  {name: "Guyana", flag: "gy"},
  {name: "Hongkong", flag: "hk"},
  {name: "Croatia", flag: "hr"},
  {name: "Haiti", flag: "ht"},
  {name: "Hungary", flag: "hu"},
  {name: "Indonesia", flag: "id"},
  {name: "Ireland", flag: "ie"},
  {name: "Israel", flag: "il"},
  {name: "Isle of Man", flag: "im"},
  {name: "India", flag: "in"},
  {name: "British Indian Ocean Territory", flag: "io"},
  {name: "Iraq", flag: "iq"},
  {name: "Iran", flag: "ir"},
  {name: "Iceland", flag: "is"},
  {name: "Italy", flag: "it"},
  {name: "Jersey", flag: "je"},
  {name: "Jamaica", flag: "jm"},
  {name: "Jordan", flag: "jo"},
  {name: "Japan", flag: "jp"},
  {name: "Kenya", flag: "ke"},
  {name: "Kyrgyzstan", flag: "kg"},
  {name: "Cambodia", flag: "kh"},
  {name: "Kiribati", flag: "ki"},
  {name: "Comoros", flag: "km"},
  {name: "Saint Kitts and Nevis", flag: "kn"},
  {name: "North Korea", flag: "kp"},
  {name: "South Korea", flag: "kr"},
  {name: "Kuwait", flag: "kw"},
  {name: "Cayman Islands", flag: "ky"},
  {name: "Kazakhstan", flag: "kz"},
  {name: "Laos", flag: "la"},
  {name: "Lebanon", flag: "lb"},
  {name: "Saint Lucia", flag: "lc"},
  {name: "Liechtenstein", flag: "li"},
  {name: "Sri Lanka", flag: "lk"},
  {name: "Liberia", flag: "lr"},
  {name: "Lesotho", flag: "ls"},
  {name: "Lithuania", flag: "lt"},
  {name: "Luxembourg", flag: "lu"},
  {name: "Latvia", flag: "lv"},
  {name: "Libya", flag: "ly"},
  {name: "Morocco", flag: "ma"},
  {name: "Monaco", flag: "mc"},
  {name: "Moldova", flag: "md"},
  {name: "Montenegro", flag: "me"},
  {name: "Madagascar", flag: "mg"},
  {name: "Marshall Islands", flag: "mh"},
  {name: "Macedonia", flag: "mk"},
  {name: "Mali", flag: "ml"},
  {name: "Myanmar", flag: "mm"},
  {name: "Mongolia", flag: "mn"},
  {name: "Macau", flag: "mo"},
  {name: "Montserrat", flag: "ms"},
  {name: "Malta", flag: "mt"},
  {name: "Mauritius", flag: "mu"},
  {name: "Maldives", flag: "mv"},
  {name: "Malawi", flag: "mw"},
  {name: "Mexico", flag: "mx"},
  {name: "Malaysia", flag: "my"},
  {name: "Mozambique", flag: "mz"},
  {name: "Namibia", flag: "na"},
  {name: "Niger", flag: "ne"},
  {name: "Norfolk Island", flag: "nf"},
  {name: "Nigeria", flag: "ng"},
  {name: "Nicaragua", flag: "ni"},
  {name: "Netherlands", flag: "nl"},
  {name: "Norway", flag: "no"},
  {name: "Nepal", flag: "np"},
  {name: "Nauru", flag: "nr"},
  {name: "Niue", flag: "nu"},
  {name: "New Zealand", flag: "nz"},
  {name: "Oman", flag: "om"},
  {name: "Panama", flag: "pa"},
  {name: "Peru", flag: "pe"},
  {name: "Polynesia", flag: "pf"},
  {name: "Papua New Guinea", flag: "pg"},
  {name: "Philippines", flag: "ph"},
  {name: "Pakistan", flag: "pk"},
  {name: "Poland", flag: "pl"},
  {name: "Pitcairn Islands", flag: "pn"},
  {name: "Puerto Rico", flag: "pr"},
  {name: "Palestine", flag: "ps"},
  {name: "Palau", flag: "pw"},
  {name: "Paraguay", flag: "py"},
  {name: "Qatar", flag: "qa"},
  {name: "Romania", flag: "ro"},
  {name: "Serbia", flag: "rs"},
  {name: "Russia", flag: "ru"},
  {name: "Rwanda", flag: "rw"},
  {name: "Saudi Arabia", flag: "sa"},
  {name: "Solomon Islands", flag: "sb"},
  {name: "Seychelles", flag: "sc"},
  {name: "Sudan", flag: "sd"},
  {name: "Sweden", flag: "se"},
  {name: "Singapore", flag: "sg"},
  {name: "Saint Helena", flag: "sh"},
  {name: "Slovenia", flag: "si"},
  {name: "Slovakia", flag: "sk"},
  {name: "Sierra Leone", flag: "sl"},
  {name: "San Marino", flag: "sm"},
  {name: "Senegal", flag: "sn"},
  {name: "Somalia", flag: "so"},
  {name: "Suriname", flag: "sr"},
  {name: "South Sudan", flag: "ss"},
  {name: "Sao Tome and Principe", flag: "st"},
  {name: "El Salvador", flag: "sv"},
  {name: "Sint Maarten", flag: "sx"},
  {name: "Syria", flag: "sy"},
  {name: "Swaziland", flag: "sz"},
  {name: "Turks and Caicos Islands", flag: "tc"},
  {name: "Chad", flag: "td"},
  {name: "French Southern and Antarctic Lands", flag: "tf"},
  {name: "Togo", flag: "tg"},
  {name: "Thailand", flag: "th"},
  {name: "Tajikistan", flag: "tj"},
  {name: "Tokelau", flag: "tk"},
  {name: "Timor-Leste", flag: "tl"},
  {name: "Turkmenistan", flag: "tm"},
  {name: "Tunisia", flag: "tn"},
  {name: "Tonga", flag: "to"},
  {name: "Turkey", flag: "tr"},
  {name: "Trinidad and Tobago", flag: "tt"},
  {name: "Tuvalu", flag: "tv"},
  {name: "Taiwan", flag: "tw"},
  {name: "Tanzania", flag: "tz"},
  {name: "Ukraine", flag: "ua"},
  {name: "Uganda", flag: "ug"},
  {name: "United States", flag: "us"},
  {name: "Uruguay", flag: "uy"},
  {name: "Uzbekistan", flag: "uz"},
  {name: "Vatican City", flag: "va"},
  {name: "Saint Vincent and The Grenadines", flag: "vc"},
  {name: "Venezuela", flag: "ve"},
  {name: "British Virgin Islands", flag: "vg"},
  {name: "United States Virgin Islands", flag: "vi"},
  {name: "Vietnam", flag: "vn"},
  {name: "Vanuatu", flag: "vu"},
  {name: "Samoa", flag: "ws"},
  {name: "Yemen", flag: "ye"}
  ])

  users = User.create([
    {name: "bob", email: "bob@101.com", password: "bob123456"},
    {name: "joe", email: "joe@101.com", password: "joe123456"},
    {name: "sam", email: "sam@101.com", password: "sam123456"},
    {name: "ted", email: "ted@101.com", password: "ted123456"}
    ])


  trails = Trail.create([
    {name: "Angel’s Landing", image: Rails.root.join("app/assets/images/trails/angel’s_landing.jpg").open, distance: 3, duration: 4, dangers: "This is a short hike that attracts a lot of people. The number of hikers can lead to traffic jams at the upper point. The route starts with a narrow sandstone ridge with steep drop-offs. During the final ascent is a steep stone staircase. The path is just wide enough for one person. If a hiker decides to pass, they’ll be scurried over the edge. Be careful when passing! The National Park Service states that at least 5 people have fallen to their death but it doesn’t include the number of people who have fallen and have been rescued.", difficulty: 2, user_id: 1, country_id: 210},
    {name: "Bright Angel Trail", image: Rails.root.join("app/assets/images/trails/bright_angel_trail.jpg").open, distance: 9, duration: 5, dangers: "This trail is not easy as many hikers think. The temperatures can reach 20 degrees hotter in the canyon than at the rim. They don’t bring enough water, fail to rest enough and start too late in the day. In addition, there have been so many injuries and near deaths that the National Park Service created a crew to help distressed hikers with heat stroke. The hike usually reaches temperatures of 110 degrees.", difficulty: 4, user_id: 1, country_id: 210},
    {name: "Cascade Saddle", image: Rails.root.join("app/assets/images/trails/cascade_saddle.jpg").open, distance: 10, duration: 48, dangers: "This hike might be famous for the Lord Of The Rings, however, it’s extremely dangerous. The views are amazing, however, there are many slippery rocks from the falls. The hike is through alpine meadows and beech forests.", difficulty: 5, user_id: 2, country_id: 153},
    {name: "El Caminito del Rey", image: Rails.root.join("app/assets/images/trails/el_caminito_del_rey.jpg").open, distance: 2, duration: 2, dangers: "The two mile trail is built on a steel path over 100 years ago. The trail was originally constructed for works to maintain a hydroelectric plant. However, over time it opened up to the public to become one of the go to dangerous hiking trails for hiking enthusiasts.", difficulty: 3, user_id: 3, country_id: 58},
    {name: "Mount Hua Shan", image: Rails.root.join("app/assets/images/trails/mount_hua_shan.jpg").open, distance: 8, duration: 7, dangers: "As history has reported, this mountain is home to pilgrims who climb to the temples at the summit. The trek contains vertical stairways, plank trails, and iron chains. Considered one of the most dangerous hikes in the world and at one point, the planks disappear and hikers must use small divots carved into the rocks to keep going.", difficulty: 5, user_id: 4, country_id: 41},
    {name: "Mount Pinatubo", image: Rails.root.join("app/assets/images/trails/mount_pinatubo.jpg").open, distance: 8, duration: 4, dangers: "More than 72 people fell victim to this hike up Mount Pinatubo’s crater lake. The last eruption was second largest recorded this century planting 15 million tons of sulfur gas onto the mountain. The hike is quite easy but the dangerous part is the volcano’s tendency to blow up again.", difficulty: 3, user_id: 2, country_id: 159},
    {name: "The Maze Canyonlands", image: Rails.root.join("app/assets/images/trails/the_maze_canyonlands.jpg").open, distance: 6, duration: 4, dangers: "Located in the Canyonlands National Park and receives around 2,000 visitors per year. The red rock labyrinth known as the Maze is full of dead ends. It’s very prone to flash floods and dangerous rockfalls. The danger can not be over emphasized and visitors must use extreme caution, communication and extreme caution.", difficulty: 4, user_id: 3, country_id: 210},
    {name: "Via Ferrata", image: Rails.root.join("app/assets/images/trails/via_ferrata.jpg").open, distance: 5, duration: 5, dangers: "Via Ferrata (Italian for “iron way”) was scaled originally by the Europeans in the 15th century. The ladders and route was used back in World War 1 by troops. The hiking trail is well maintained with cables, ropes, wooden walkways, and suspension bridges. Your life depends on safety hinges snapping into a specialized carabiner setup (called a ferrata set). The dangerous parts of the hike include the rock faces and the tall ledges that you have to scale to complete the hike.", difficulty: 4, user_id: 4, country_id: 97},
    {name: "West Coast Trail", image: Rails.root.join("app/assets/images/trails/west_coast_trail.jpg").open, distance: 47, duration: 168, dangers: "Despite a relatively low death rate compared to some of the other hikes on this list, the West Coast Trail’s long, almost vertical ladder sections make it a real thrill-seeker’s hiking trail. The terrain is consistently uneven.
Hikers should be equipped to wade through rivers, scramble across steep slopes and be prepared for slippery conditions throughout. Storms regularly damage the trails and structures, making them even more dangerous or often impassable. Oh, and did I mention that one may encounter the odd bear or cougar en route?", difficulty: 5, user_id: 2, country_id: 35},
    {name: "Kokoda Trail", image: Rails.root.join("app/assets/images/trails/kokoda_trail.jpg").open, distance: 60, duration: 288, dangers: "The Kokoda Track has seen plenty of death in its time. In 1942, it was the scene of intense fighting between the Japanese and Australians. The route lay almost dormant until the past decade, when adventurous trekkers discovered the 60-mile slog connecting the outskirts of Port Moresby to the village of Kokoda.
In 2009, 13 people died in a plane crash en route to the trailhead, and four more hikers died on the trail, which takes up to 11 days to complete. They faced malaria, extreme heat, frigid nights, and daily bone-soaking afternoon rains. The route itself has been called a StairMaster in a steam room, with ankle-deep clay muck, slippery roots, and portions that become waterfalls. As you might expect, the death toll and the harsh conditions started to deter trekkers.
Since the ill-fated 2009 season, the governments of Australia and Papua New Guinea have spent millions of dollars bringing more modern facilities to the trail. You still have to watch out for all the dangers listed above, but the wild route is changing rapidly.
", difficulty: 5, user_id: 3, country_id: 158},
    {name: "Huayna Picchu Trail", image: Rails.root.join("app/assets/images/trails/huayna_picchu_trail.jpg").open, distance: 1, duration: 2, dangers: "The Inca Trail to Machu Picchu can be a tough trek, and it takes a few casualties each year. But the real danger begins when you follow the trail past the mythical city and up Huayna Picchu, aka the “Hike of Death.” The old Inca staircase is carved out of granite and climbs about 1,000 feet in less than a mile. Plus, the route is full of rotting, crumbling rock, slippery stones, and exposed corners. Many people tackle the route totally unprepared—we’re talking flip-flops and no water.
Clouds and mist make the journey more difficult, and in some sections hikers must cling to old steel cables. Going up is the easy part. Coming down the steep slope often paralyzes travelers with fear. But it’s worth the pain—the view from Huayna Picchu on a sunny day is the best bird’s-eye view of Machu Picchu below.", difficulty: 2, user_id: 4, country_id: 156},
    {name: "Pacaya Volcano", image: Rails.root.join("app/assets/images/trails/pacaya_volcano.jpg").open, distance: 4, duration: 4, dangers: "Active volcanoes typically aren't top tourist attractions, but Guatemala's Pacaya, located near the capital city, is different. Pacaya became active again in 1965. Since then, eruptions have killed a handful of people. A 2010 eruption claimed three lives, and another eruption three years later sent lava flowing down one side of the mountain. Nearby villages were evacuated. Pacaya began spewing rocks, ash, and vapor again last March.
The climb can be dangerous even when the volcano isn't erupting. Hikers have made it to the top of the mountain's steep cinder cone, only to fall in thanks to the hot, crumbling ground.
The national park service closed the 8,000-foot peak to the public after the fatalities, but some stubborn trekkers are still reportedly accessing the volcano from nearby farms.", difficulty: 3, user_id: 1, country_id: 80}
    ])


  comments = Comment.create([
    {content: "Carry as little as possible, but choose that little with care.", user_id: 1, trail_id: 2},
    {content: "Make sure to bring lots of water! This trail is long and it gets really hot.", user_id: 2, trail_id: 2},
    {content: "There are several animals that inhabit the area around the Cascade Saddle trail, including cougars, black bears, beaver, foxes, falcons, porcupines and more!", user_id: 1, trail_id: 3},
    {content: "The hike to the end point and back is under 5 miles round-trip and gains less than 200 feet of elevation, making it a pretty good trip for families with kids who can be coerced onto the trail.", user_id: 3, trail_id: 3},
    {content: "There's no view more dramatic than what you see hanging onto a chain bolted into a cliff.", user_id: 4, trail_id: 1},
    {content: "The Cascade Saddle Route is an alpine crossing recommended for experienced trampers as a fine weather, summer route.", user_id: 4, trail_id: 3},
    {content: "The views of Zion Canyon's 270 million-year-old rock layers will time travel you back to the Triassic period when this section of the Colorado Plateau was a flat basin at sea level.", user_id: 2, trail_id: 1}
    ])
